apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::997847477807:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1EWQXOSKR1OT8
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::997847477807:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-07T14:13:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1487"
  uid: 46cea8ab-5283-4cd3-a0ce-e71eb6436bf2
